name: medlink_connect
description: "Cross-platform network facilitator for hospital RDP access."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.7.0
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  url_launcher_linux: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
